# yazi.toml
[mgr]
# It seems that it doesn't work O.o
show_hidden = true

[[plugin.prepend_fetchers]]
id    = "git"
name  = "*"
run   = "git"
group = "mime"
mime  = "*/*"

[[plugin.prepend_fetchers]]
id    = "git"
name  = "*/"
run   = "git"
group = "mime"
mime  = "inode/directory"
