events {}
http {
    # ODOO Server
    resolver 127.0.0.11 valid=30s;  # Docker internal DNS
    server {
        listen 80;
        server_name dev.localhost;

        location / {
            set $odoo "odoo:8069";        # container name, dynamic resolution
            proxy_pass http://$odoo;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name dev1.localhost;

        location / {
            set $odoo2 "odoo2:8070";        # container name, dynamic resolution
            proxy_pass http://$odoo2;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
